Fix filename space
EliuX/MEGAcmd4J pull request #33
Opened 2021-06-29 14:32 UTC by gringofe

# Description
When calling `MegaCmdList#ls` files with spaces are just ignored. This PR fixes this. 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

1. Create a file with a space
2. Run a `MegaCmdList#ls` in the directory of the file
3. It now shows up in the list
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2021-06-29 18:27 UTC, gringofe commented
Directories with spaces only work sometimes, what the hell?

2021-06-29 18:38 UTC, gringofe commented
This PR seems not ready, will reopen when it's working properly

2021-06-29 20:07 UTC, EliuX requested changes
Thanks for this contribution. I would like to see the tests of those cases you want to prevent in order to determinate whether this is a good solution. For instance you could create a folder and or file with a space and check out whether this is actually being listed.

2021-06-30 00:30 UTC, EliuX commented on src/main/java/io/github/eliux/mega/cmd/MegaCmdList.java
> +        int skipNLines = remotePath.contains(" ") ? 2 : 1;
That test you mention in the description of the PR should be written in code, otherwise it wont persist and reevaluated in the future.

2021-06-30 03:49 UTC, EliuX commented
Please check out https://github.com/EliuX/MEGAcmd4J/pull/35

2021-06-30 07:50 UTC, gringofe commented
#35 seems to work.

2021-06-30 23:39 UTC, closed without merging